### PR TITLE
Add ability to configure shared_preload_libraries, max_worker_processes and track_commit_timestamp settings

### PR DESCRIPTION
**Pull request by chtitux**

### CODE REVIEW

**Comment by misdoro** [comment]
LGTM.
I'm wondering if we should not document all the possible keys of the `postgres_extra_config` somewhere

**Comment by paulRbr** [comment]
Could you also parametrise the config `max_connections` please? I find the default value of this role (`400`) way too high. :pray: Thank youu

**Comment by paulRbr** [comment]
> LGTM.
> I'm wondering if we should not document all the possible keys of the `postgres_extra_config` somewhere

Yeh, the `extra_config` parameter available for each cluster of the `postgres_clusters` array is not even documented [in the readme](https://github.com/trainline-eu/ansible-postgresql-role#variables). It would be nice to at least mention it :blush:

**Comment by chtitux** [comment]
`extra_config` documentation added, `max_connections` added and set to 100 (default value)

**Pull request merged**
